import type { Exercise } from "../types";

export const ARMS: Exercise[] = [
  // ─── 二頭肌 Biceps ──────────────────────────────────
  {
    id: "barbell-curl",
    name_zh: "槓鈴彎舉",
    name_en: "Barbell Curl",
    category: "手臂",
    movement_pattern: "孤立訓練",
    equipment: ["槓鈴", "EZ槓"],
    primary_muscles: ["二頭肌"],
    secondary_muscles: ["前臂"],
    muscle_emphasis_note: "主要刺激二頭肌長頭與短頭，前臂協同。直槓重壓二頭、EZ 槓對手腕較友善。",
    variations: [
      { id: "straight", name_zh: "直槓彎舉", note: "標準版本，最大化二頭整體刺激" },
      { id: "ez", name_zh: "EZ 槓彎舉", emphasis_change: "手腕舒適", note: "適合手腕不適者" },
      { id: "narrow", name_zh: "窄握彎舉", emphasis_change: "偏二頭長頭" },
      { id: "wide", name_zh: "寬握彎舉", emphasis_change: "偏二頭短頭" },
    ],
    suitable_for: "所有程度",
    fatigue_level: "中",
    skill_level: "中",
    ai_programming_note: "適合放在手臂日中段作為二頭主動作。新手優先用 EZ 槓。",
    default_rep_range: [8, 12],
  },
  {
    id: "dumbbell-curl",
    name_zh: "啞鈴彎舉",
    name_en: "Dumbbell Curl",
    category: "手臂",
    movement_pattern: "孤立訓練",
    equipment: ["啞鈴"],
    primary_muscles: ["二頭肌"],
    secondary_muscles: ["前臂"],
    muscle_emphasis_note: "可雙手同時或交替；交替版本在募集二頭時更專注，雙手版較省時。",
    variations: [
      { id: "alt", name_zh: "單手交替彎舉" },
      { id: "both", name_zh: "雙手同時彎舉" },
      { id: "seated", name_zh: "坐姿啞鈴彎舉", note: "減少上身代償" },
      { id: "standing", name_zh: "站姿啞鈴彎舉" },
    ],
    suitable_for: "所有程度",
    fatigue_level: "中",
    skill_level: "低",
    ai_programming_note: "新手友善，動作自由度高。常作為二頭主動作或補充。",
    default_rep_range: [8, 12],
  },
  {
    id: "hammer-curl",
    name_zh: "錘式彎舉",
    name_en: "Hammer Curl",
    category: "手臂",
    movement_pattern: "孤立訓練",
    equipment: ["啞鈴", "繩索", "滑輪"],
    primary_muscles: ["肱橈肌", "二頭肌長頭"],
    secondary_muscles: ["前臂"],
    muscle_emphasis_note: "中立握把刺激肱橈肌與二頭長頭，能讓前臂與整體手臂變粗。",
    variations: [
      { id: "dumbbell", name_zh: "啞鈴錘式彎舉" },
      { id: "rope", name_zh: "繩索錘式彎舉", note: "持續張力較佳" },
    ],
    suitable_for: "所有程度",
    fatigue_level: "低",
    skill_level: "低",
    ai_programming_note: "適合手臂日後段作為前臂與二頭長頭加強。",
    default_rep_range: [10, 15],
  },
  {
    id: "incline-dumbbell-curl",
    name_zh: "斜板啞鈴彎舉",
    name_en: "Incline Dumbbell Curl",
    category: "手臂",
    movement_pattern: "孤立訓練",
    equipment: ["啞鈴", "斜板"],
    primary_muscles: ["二頭肌長頭"],
    secondary_muscles: ["前臂"],
    muscle_emphasis_note: "斜板讓二頭處於拉伸位置，主要刺激二頭肌長頭。",
    suitable_for: "中階",
    fatigue_level: "中",
    skill_level: "中",
    ai_programming_note: "進階二頭塑形動作，建議放在二頭主動作之後。",
    default_rep_range: [10, 12],
  },
  {
    id: "cable-curl",
    name_zh: "滑輪彎舉",
    name_en: "Cable Curl",
    category: "手臂",
    movement_pattern: "孤立訓練",
    equipment: ["滑輪", "繩索"],
    primary_muscles: ["二頭肌"],
    secondary_muscles: ["前臂"],
    muscle_emphasis_note: "滑輪提供持續張力，整段動作刺激均勻，特別適合收縮感受度。",
    variations: [
      { id: "bar", name_zh: "直桿滑輪彎舉" },
      { id: "rope", name_zh: "繩索滑輪彎舉", note: "可在頂端外旋強化收縮" },
      { id: "single", name_zh: "單手滑輪彎舉", note: "可從不同角度練二頭" },
    ],
    suitable_for: "所有程度",
    fatigue_level: "中",
    skill_level: "低",
    ai_programming_note: "適合放在手臂日後段強化感受度。新手可用作主動作。",
    default_rep_range: [10, 15],
  },
  {
    id: "concentration-curl",
    name_zh: "集中彎舉",
    name_en: "Concentration Curl",
    category: "手臂",
    movement_pattern: "孤立訓練",
    equipment: ["啞鈴"],
    primary_muscles: ["二頭肌"],
    secondary_muscles: [],
    muscle_emphasis_note: "坐姿單手版本，把手肘卡在大腿內側，最大化二頭收縮控制。",
    suitable_for: "所有程度",
    fatigue_level: "低",
    skill_level: "低",
    ai_programming_note: "適合手臂日收尾動作；用較輕重量追求感受度。",
    default_rep_range: [10, 15],
  },

  // ─── 三頭肌 Triceps ─────────────────────────────────
  {
    id: "triceps-pushdown",
    name_zh: "滑輪下壓",
    name_en: "Triceps Pushdown",
    category: "手臂",
    movement_pattern: "孤立訓練",
    equipment: ["滑輪", "繩索"],
    primary_muscles: ["三頭肌"],
    secondary_muscles: ["前臂"],
    muscle_emphasis_note: "三頭肌外側頭與內側頭主刺激，繩索版本可在底部外展強化收縮。",
    variations: [
      { id: "bar", name_zh: "直桿下壓" },
      { id: "v", name_zh: "V 把下壓" },
      { id: "rope", name_zh: "繩索下壓", note: "底部外展強化感受" },
      { id: "single", name_zh: "單手下壓" },
      { id: "reverse", name_zh: "反握下壓", emphasis_change: "偏內側頭" },
    ],
    suitable_for: "所有程度",
    fatigue_level: "低",
    skill_level: "低",
    ai_programming_note: "新手友善的三頭主動作，幾乎所有人手臂日都能放。",
    default_rep_range: [10, 15],
  },
  {
    id: "overhead-cable-extension",
    name_zh: "繩索過頭伸展",
    name_en: "Overhead Cable Extension",
    category: "手臂",
    movement_pattern: "孤立訓練",
    equipment: ["滑輪", "繩索"],
    primary_muscles: ["三頭肌長頭"],
    secondary_muscles: ["三頭肌外側頭"],
    muscle_emphasis_note: "過頭姿勢拉伸三頭長頭，是塑形上臂後側的關鍵動作。",
    suitable_for: "所有程度",
    fatigue_level: "中",
    skill_level: "中",
    ai_programming_note: "三頭日中段，補強長頭，配合下壓會更完整。",
    default_rep_range: [10, 12],
  },
  {
    id: "close-grip-bench",
    name_zh: "窄握臥推",
    name_en: "Close-Grip Bench Press",
    category: "手臂",
    movement_pattern: "推",
    equipment: ["槓鈴", "板凳"],
    primary_muscles: ["三頭肌"],
    secondary_muscles: ["胸大肌", "肩前束"],
    muscle_emphasis_note: "三頭肌為主，胸與肩前束輔助；屬於複合三頭動作。",
    suitable_for: "中階",
    fatigue_level: "高",
    skill_level: "中",
    ai_programming_note: "三頭主動作，適合放在手臂或推日的前段。新手先用機械胸推 + 下壓替代。",
    default_rep_range: [6, 10],
    is_compound_main: true,
  },
  {
    id: "skull-crusher",
    name_zh: "仰臥臂屈伸",
    name_en: "Skull Crusher",
    category: "手臂",
    movement_pattern: "孤立訓練",
    equipment: ["EZ槓", "槓鈴", "板凳"],
    primary_muscles: ["三頭肌長頭"],
    secondary_muscles: ["三頭肌外側頭"],
    muscle_emphasis_note: "肘關節屈伸，主刺激三頭肌長頭。EZ 槓對手腕較友善。",
    suitable_for: "中階",
    fatigue_level: "中",
    skill_level: "中",
    ai_programming_note: "進階三頭塑形動作；新手手肘不適者改用滑輪下壓。",
    default_rep_range: [8, 12],
  },
  {
    id: "dips",
    name_zh: "雙槓撐體",
    name_en: "Dips",
    category: "手臂",
    movement_pattern: "推",
    equipment: ["雙槓"],
    primary_muscles: ["三頭肌", "胸大肌下部"],
    secondary_muscles: ["肩前束"],
    muscle_emphasis_note: "身體較直偏三頭，身體前傾偏胸；徒手大重量複合動作。",
    variations: [
      { id: "upright", name_zh: "直立 Dips", emphasis_change: "偏三頭" },
      { id: "leaning", name_zh: "前傾 Dips", emphasis_change: "偏下胸" },
    ],
    suitable_for: "中階",
    fatigue_level: "高",
    skill_level: "中",
    ai_programming_note: "進階徒手動作。新手體重不足以做時用輔助 Dips 機。",
    default_rep_range: [6, 12],
    is_compound_main: true,
  },
];
