import type { Exercise } from "../types";

export const BACK: Exercise[] = [
  // ─── 垂直拉：背寬 ────────────────────────────────────
  {
    id: "pull-up",
    name_zh: "引體向上",
    name_en: "Pull-Up",
    category: "背部",
    movement_pattern: "拉",
    equipment: ["引體向上桿"],
    primary_muscles: ["背闊肌"],
    secondary_muscles: ["二頭肌", "下斜方肌", "核心"],
    muscle_emphasis_note: "經典背寬王牌動作；不同握法刺激不同。",
    variations: [
      { id: "overhand", name_zh: "正握引體向上" },
      { id: "underhand", name_zh: "反握引體向上 (Chin-Up)", emphasis_change: "二頭參與更多" },
      { id: "neutral", name_zh: "中立握引體向上" },
      { id: "wide", name_zh: "寬握引體向上", emphasis_change: "背寬" },
      { id: "narrow", name_zh: "窄握引體向上" },
      { id: "assisted", name_zh: "輔助引體向上機", note: "新手起點" },
      { id: "band", name_zh: "彈力帶輔助引體向上" },
      { id: "weighted", name_zh: "負重引體向上", note: "進階" },
      { id: "eccentric", name_zh: "離心引體向上", note: "做不到一下時用" },
    ],
    suitable_for: "中階",
    fatigue_level: "高",
    skill_level: "中",
    ai_programming_note: "背日主動作；新手用輔助機或彈力帶。",
    default_rep_range: [4, 10],
    is_compound_main: true,
  },
  {
    id: "lat-pulldown",
    name_zh: "高位下拉",
    name_en: "Lat Pulldown",
    category: "背部",
    movement_pattern: "拉",
    equipment: ["滑輪"],
    primary_muscles: ["背闊肌"],
    secondary_muscles: ["二頭肌", "菱形肌"],
    muscle_emphasis_note: "引體向上的最佳替代；負重可調，新手必排。",
    variations: [
      { id: "wide", name_zh: "寬握下拉", emphasis_change: "背寬" },
      { id: "narrow", name_zh: "窄握下拉" },
      { id: "underhand", name_zh: "反握下拉", emphasis_change: "下背闊與二頭" },
      { id: "neutral", name_zh: "中立握下拉" },
      { id: "v", name_zh: "V 把下拉" },
      { id: "single", name_zh: "單手高位下拉" },
      { id: "kneeling", name_zh: "跪姿單手滑輪下拉" },
    ],
    suitable_for: "所有程度",
    fatigue_level: "中",
    skill_level: "低",
    ai_programming_note: "新手 / 恢復期背日主動作。",
    default_rep_range: [8, 12],
    is_compound_main: true,
  },
  {
    id: "straight-arm-pulldown",
    name_zh: "直臂下拉",
    name_en: "Straight-Arm Pulldown",
    category: "背部",
    movement_pattern: "孤立訓練",
    equipment: ["滑輪", "繩索"],
    primary_muscles: ["背闊肌"],
    secondary_muscles: ["核心"],
    muscle_emphasis_note: "肘關節不彎，孤立背闊肌；非常適合喚醒背闊感受度。",
    variations: [
      { id: "bar", name_zh: "直桿直臂下拉" },
      { id: "rope", name_zh: "繩索直臂下拉" },
      { id: "single", name_zh: "單手直臂下拉" },
    ],
    suitable_for: "所有程度",
    fatigue_level: "低",
    skill_level: "中",
    ai_programming_note: "可放在背日前段喚醒背闊；2-3 組 12-15 下。",
    default_rep_range: [10, 15],
  },
  {
    id: "single-arm-cable-pulldown",
    name_zh: "單手滑輪下拉",
    name_en: "Single-Arm Cable Lat Pulldown",
    category: "背部",
    movement_pattern: "拉",
    equipment: ["滑輪"],
    primary_muscles: ["背闊肌"],
    secondary_muscles: ["核心"],
    muscle_emphasis_note: "活動範圍更大、可從不同角度刺激背闊。",
    suitable_for: "中階",
    fatigue_level: "中",
    skill_level: "中",
    ai_programming_note: "背日中後段加強單側感受度。",
    default_rep_range: [10, 15],
  },
  {
    id: "machine-pulldown",
    name_zh: "機械下拉",
    name_en: "Machine Pulldown",
    category: "背部",
    movement_pattern: "拉",
    equipment: ["機械"],
    primary_muscles: ["背闊肌"],
    secondary_muscles: ["二頭肌"],
    muscle_emphasis_note: "軌道固定的下拉版本；新手友善。",
    suitable_for: "所有程度",
    fatigue_level: "中",
    skill_level: "低",
    ai_programming_note: "缺滑輪時的替代背部主動作。",
    default_rep_range: [8, 12],
  },

  // ─── 水平拉：背厚 ────────────────────────────────────
  {
    id: "seated-cable-row",
    name_zh: "坐姿划船",
    name_en: "Seated Cable Row",
    category: "背部",
    movement_pattern: "拉",
    equipment: ["滑輪"],
    primary_muscles: ["中背", "背闊肌"],
    secondary_muscles: ["菱形肌", "斜方肌中束", "二頭肌"],
    muscle_emphasis_note: "背厚主動作；持續張力、新手友善。",
    variations: [
      { id: "v", name_zh: "V 把坐姿划船" },
      { id: "wide", name_zh: "寬握坐姿划船" },
      { id: "bar", name_zh: "直桿坐姿划船" },
      { id: "single", name_zh: "單手坐姿划船" },
      { id: "high", name_zh: "高位划船", emphasis_change: "上背 / 後三角" },
      { id: "low", name_zh: "低位划船", emphasis_change: "背闊下部" },
    ],
    suitable_for: "所有程度",
    fatigue_level: "中",
    skill_level: "低",
    ai_programming_note: "新手背日水平拉首選。",
    default_rep_range: [8, 12],
    is_compound_main: true,
  },
  {
    id: "barbell-row",
    name_zh: "槓鈴划船",
    name_en: "Barbell Row",
    category: "背部",
    movement_pattern: "拉",
    equipment: ["槓鈴"],
    primary_muscles: ["背闊肌", "中背"],
    secondary_muscles: ["後三角", "下背", "二頭肌"],
    muscle_emphasis_note: "全背複合動作；下背須主動穩定。",
    variations: [
      { id: "overhand", name_zh: "正握槓鈴划船" },
      { id: "underhand", name_zh: "反握槓鈴划船 (Yates Row)", emphasis_change: "背闊更多" },
      { id: "pendlay", name_zh: "Pendlay Row", note: "每下放回地面、爆發拉" },
      { id: "smith", name_zh: "史密斯機划船" },
    ],
    suitable_for: "中階",
    fatigue_level: "高",
    skill_level: "中",
    ai_programming_note: "背日主動作；新手先用啞鈴或胸靠版本。",
    default_rep_range: [6, 10],
    is_compound_main: true,
  },
  {
    id: "dumbbell-row",
    name_zh: "啞鈴單手划船",
    name_en: "One-Arm Dumbbell Row",
    category: "背部",
    movement_pattern: "拉",
    equipment: ["啞鈴", "板凳"],
    primary_muscles: ["背闊肌", "中背"],
    secondary_muscles: ["後三角", "二頭肌"],
    muscle_emphasis_note: "單側划船；活動範圍大、可專注感受。",
    variations: [
      { id: "bench", name_zh: "單手扶椅啞鈴划船" },
      { id: "three", name_zh: "三點支撐啞鈴划船" },
      { id: "double", name_zh: "雙啞鈴俯身划船" },
      { id: "kroc", name_zh: "Kroc Row", note: "高次數高重量、爆發版本" },
    ],
    suitable_for: "所有程度",
    fatigue_level: "中",
    skill_level: "中",
    ai_programming_note: "新手友善的水平拉動作；單側 8-12 下。",
    default_rep_range: [8, 12],
  },
  {
    id: "chest-supported-row",
    name_zh: "胸靠划船",
    name_en: "Chest-Supported Row",
    category: "背部",
    movement_pattern: "拉",
    equipment: ["啞鈴", "斜板", "T槓", "機械"],
    primary_muscles: ["中背", "背闊肌"],
    secondary_muscles: ["後三角"],
    muscle_emphasis_note: "胸靠在斜板，去除下背承擔；最容易感受中背。",
    variations: [
      { id: "dumbbell", name_zh: "胸靠啞鈴划船" },
      { id: "tbar", name_zh: "胸靠 T-Bar Row" },
      { id: "machine", name_zh: "胸靠機械划船" },
      { id: "incline", name_zh: "上斜椅啞鈴划船" },
    ],
    suitable_for: "所有程度",
    fatigue_level: "中",
    skill_level: "低",
    ai_programming_note: "下背疲勞 / 想保護下背時的水平拉首選。",
    default_rep_range: [8, 12],
  },
  {
    id: "tbar-row",
    name_zh: "T-Bar Row",
    name_en: "T-Bar Row",
    category: "背部",
    movement_pattern: "拉",
    equipment: ["T槓", "地雷管", "槓鈴"],
    primary_muscles: ["中背", "背闊肌"],
    secondary_muscles: ["斜方肌", "後三角"],
    muscle_emphasis_note: "中背肥大動作；可調握把改變刺激。",
    variations: [
      { id: "trad", name_zh: "傳統 T-Bar" },
      { id: "chest", name_zh: "胸靠 T-Bar" },
      { id: "landmine", name_zh: "地雷管 T-Bar" },
      { id: "wide", name_zh: "寬握 T-Bar", emphasis_change: "背寬" },
      { id: "narrow", name_zh: "窄握 T-Bar", emphasis_change: "中背" },
    ],
    suitable_for: "中階",
    fatigue_level: "高",
    skill_level: "中",
    ai_programming_note: "中階以上中背主動作。",
    default_rep_range: [6, 10],
    is_compound_main: true,
  },
  {
    id: "machine-row",
    name_zh: "機械划船",
    name_en: "Machine Row",
    category: "背部",
    movement_pattern: "拉",
    equipment: ["機械"],
    primary_muscles: ["中背", "背闊肌"],
    secondary_muscles: ["二頭肌"],
    muscle_emphasis_note: "軌道固定；非常新手友善。",
    suitable_for: "所有程度",
    fatigue_level: "中",
    skill_level: "低",
    ai_programming_note: "恢復習慣期背日水平拉首選。",
    default_rep_range: [8, 12],
  },
  {
    id: "inverted-row",
    name_zh: "反向划船",
    name_en: "Inverted Row",
    category: "背部",
    movement_pattern: "拉",
    equipment: ["徒手", "槓鈴"],
    primary_muscles: ["中背", "背闊肌"],
    secondary_muscles: ["核心", "後三角"],
    muscle_emphasis_note: "徒手水平拉；身體愈水平愈難。",
    suitable_for: "所有程度",
    fatigue_level: "中",
    skill_level: "低",
    ai_programming_note: "無滑輪/機械時的徒手背部首選。",
    default_rep_range: [8, 15],
  },

  // ─── 上背 / 後三角 ──────────────────────────────────
  {
    id: "reverse-fly",
    name_zh: "反向飛鳥",
    name_en: "Reverse Fly",
    category: "背部",
    movement_pattern: "孤立訓練",
    equipment: ["啞鈴", "機械", "滑輪"],
    primary_muscles: ["後三角", "中上背"],
    secondary_muscles: ["菱形肌"],
    muscle_emphasis_note: "後三角孤立動作；姿勢不良族必排。",
    variations: [
      { id: "dumbbell", name_zh: "啞鈴俯身反向飛鳥" },
      { id: "machine", name_zh: "反向蝴蝶機" },
      { id: "cable", name_zh: "滑輪反向飛鳥" },
      { id: "chest", name_zh: "胸靠反向飛鳥" },
    ],
    suitable_for: "所有程度",
    fatigue_level: "低",
    skill_level: "低",
    ai_programming_note: "肩日 / 拉日 / 背日尾段必排。",
    default_rep_range: [12, 15],
  },
  {
    id: "high-row",
    name_zh: "高位划船",
    name_en: "High Row",
    category: "背部",
    movement_pattern: "拉",
    equipment: ["機械", "滑輪"],
    primary_muscles: ["上背", "後三角"],
    secondary_muscles: ["背闊上部"],
    muscle_emphasis_note: "拉的角度從上斜下；上背刺激最直接。",
    suitable_for: "所有程度",
    fatigue_level: "中",
    skill_level: "低",
    ai_programming_note: "背日中後段補強上背。",
    default_rep_range: [10, 12],
  },

  // ─── 下背 / 後側鏈 ──────────────────────────────────
  {
    id: "rack-pull",
    name_zh: "Rack Pull",
    name_en: "Rack Pull",
    category: "背部",
    movement_pattern: "髖鉸鏈",
    equipment: ["槓鈴"],
    primary_muscles: ["上背", "下背", "臀大肌"],
    secondary_muscles: ["握力", "斜方肌"],
    muscle_emphasis_note: "從膝蓋上方開始的硬舉，可推較大重量、刺激上背更多。",
    suitable_for: "中階",
    fatigue_level: "高",
    skill_level: "中",
    ai_programming_note: "背日 / 拉日的下背主動作；技術較傳統硬舉容易。",
    default_rep_range: [5, 8],
    is_compound_main: true,
  },

  // ─── 背部孤立 / 感受度 ──────────────────────────────
  {
    id: "kneeling-single-pulldown",
    name_zh: "單手跪姿下拉",
    name_en: "Kneeling Single-Arm Pulldown",
    category: "背部",
    movement_pattern: "拉",
    equipment: ["滑輪"],
    primary_muscles: ["背闊肌"],
    secondary_muscles: ["核心"],
    muscle_emphasis_note: "跪姿讓骨盆穩定，背闊孤立度更高。",
    suitable_for: "所有程度",
    fatigue_level: "低",
    skill_level: "中",
    ai_programming_note: "背日尾段加強感受度。",
    default_rep_range: [10, 15],
  },
];
