import type { Exercise } from "../types";

export const CHEST: Exercise[] = [
  // ─── 推舉類 ──────────────────────────────────────────
  {
    id: "barbell-bench-press",
    name_zh: "平板槓鈴臥推",
    name_en: "Barbell Bench Press",
    category: "胸部",
    movement_pattern: "推",
    equipment: ["槓鈴", "板凳"],
    primary_muscles: ["胸大肌"],
    secondary_muscles: ["三頭肌", "肩前束"],
    muscle_emphasis_note: "胸大肌中部主刺激；最具負荷潛力的胸推動作。",
    suitable_for: "中階",
    fatigue_level: "高",
    skill_level: "中",
    ai_programming_note: "胸日主動作首選。新手先用機械胸推或啞鈴。",
    default_rep_range: [5, 8],
    is_compound_main: true,
  },
  {
    id: "dumbbell-bench-press",
    name_zh: "平板啞鈴臥推",
    name_en: "Dumbbell Bench Press",
    category: "胸部",
    movement_pattern: "推",
    equipment: ["啞鈴", "板凳"],
    primary_muscles: ["胸大肌"],
    secondary_muscles: ["三頭肌", "肩前束"],
    muscle_emphasis_note: "活動度大於槓鈴；雙手獨立修正不平衡。",
    suitable_for: "所有程度",
    fatigue_level: "高",
    skill_level: "中",
    ai_programming_note: "胸日主動作 / 副主動作。",
    default_rep_range: [6, 12],
    is_compound_main: true,
  },
  {
    id: "incline-barbell-bench",
    name_zh: "上斜槓鈴臥推",
    name_en: "Incline Barbell Bench Press",
    category: "胸部",
    movement_pattern: "推",
    equipment: ["槓鈴", "斜板"],
    primary_muscles: ["上胸"],
    secondary_muscles: ["肩前束", "三頭肌"],
    muscle_emphasis_note: "30–45 度斜板，刺激上胸鎖骨段。",
    suitable_for: "中階",
    fatigue_level: "高",
    skill_level: "中",
    ai_programming_note: "胸日主動作。想練上胸者優先。",
    default_rep_range: [6, 10],
    is_compound_main: true,
  },
  {
    id: "incline-dumbbell-press",
    name_zh: "上斜啞鈴臥推",
    name_en: "Incline Dumbbell Press",
    category: "胸部",
    movement_pattern: "推",
    equipment: ["啞鈴", "斜板"],
    primary_muscles: ["上胸"],
    secondary_muscles: ["肩前束", "三頭肌"],
    muscle_emphasis_note: "上胸主動作；活動度大於槓鈴版本。",
    suitable_for: "所有程度",
    fatigue_level: "高",
    skill_level: "中",
    ai_programming_note: "胸日上胸主動作；新手友善。",
    default_rep_range: [8, 12],
    is_compound_main: true,
  },
  {
    id: "decline-bench-press",
    name_zh: "下斜臥推",
    name_en: "Decline Bench Press",
    category: "胸部",
    movement_pattern: "推",
    equipment: ["槓鈴", "斜板"],
    primary_muscles: ["下胸"],
    secondary_muscles: ["三頭肌"],
    muscle_emphasis_note: "刺激胸大肌下部；肩關節壓力較小。",
    suitable_for: "中階",
    fatigue_level: "中",
    skill_level: "中",
    ai_programming_note: "下胸補強；非必要動作，平板已含下胸刺激。",
    default_rep_range: [8, 12],
  },
  {
    id: "machine-chest-press",
    name_zh: "機械胸推",
    name_en: "Machine Chest Press",
    category: "胸部",
    movement_pattern: "推",
    equipment: ["機械"],
    primary_muscles: ["胸大肌"],
    secondary_muscles: ["三頭肌", "肩前束"],
    muscle_emphasis_note: "軌道固定、最容易學習；新手與恢復期首選。",
    suitable_for: "所有程度",
    fatigue_level: "中",
    skill_level: "低",
    ai_programming_note: "新手與恢復習慣者的胸日主動作。",
    default_rep_range: [8, 12],
  },
  {
    id: "smith-bench-press",
    name_zh: "史密斯臥推",
    name_en: "Smith Machine Bench Press",
    category: "胸部",
    movement_pattern: "推",
    equipment: ["史密斯機"],
    primary_muscles: ["胸大肌"],
    secondary_muscles: ["三頭肌", "肩前束"],
    muscle_emphasis_note: "軌道固定的槓鈴臥推；可單人安全推大重量。",
    variations: [
      { id: "flat", name_zh: "平板史密斯臥推" },
      { id: "incline", name_zh: "上斜史密斯臥推", emphasis_change: "上胸" },
      { id: "decline", name_zh: "下斜史密斯臥推", emphasis_change: "下胸" },
    ],
    suitable_for: "所有程度",
    fatigue_level: "高",
    skill_level: "低",
    ai_programming_note: "獨自訓練、缺保護者的最佳臥推替代。",
    default_rep_range: [6, 12],
  },
  {
    id: "landmine-chest-press",
    name_zh: "地雷管胸推",
    name_en: "Landmine Chest Press",
    category: "胸部",
    movement_pattern: "推",
    equipment: ["地雷管", "槓鈴"],
    primary_muscles: ["上胸", "肩前束"],
    secondary_muscles: ["核心", "三頭肌"],
    muscle_emphasis_note: "斜上推、肩關節壓力低，適合肩膀不適者。",
    suitable_for: "所有程度",
    fatigue_level: "中",
    skill_level: "低",
    ai_programming_note: "肩膀疼痛時的臥推替代品。",
    default_rep_range: [8, 12],
  },

  // ─── 飛鳥 / 夾胸類 ────────────────────────────────────
  {
    id: "cable-fly",
    name_zh: "滑輪夾胸",
    name_en: "Cable Fly",
    category: "胸部",
    movement_pattern: "孤立訓練",
    equipment: ["滑輪"],
    primary_muscles: ["胸大肌"],
    secondary_muscles: ["肩前束"],
    muscle_emphasis_note: "持續張力、底部不卸載；可改變滑輪高度刺激不同部位。",
    variations: [
      { id: "high", name_zh: "高位滑輪夾胸", emphasis_change: "偏下胸" },
      { id: "mid", name_zh: "中位滑輪夾胸", emphasis_change: "中胸" },
      { id: "low", name_zh: "低位滑輪夾胸", emphasis_change: "偏上胸" },
    ],
    suitable_for: "所有程度",
    fatigue_level: "中",
    skill_level: "低",
    ai_programming_note: "胸日中後段塑形動作；改高度可補強弱項。",
    default_rep_range: [10, 15],
  },
  {
    id: "pec-deck",
    name_zh: "蝴蝶機夾胸",
    name_en: "Pec Deck",
    category: "胸部",
    movement_pattern: "孤立訓練",
    equipment: ["機械"],
    primary_muscles: ["胸大肌"],
    secondary_muscles: [],
    muscle_emphasis_note: "胸大肌內收最易感受度動作，對新手極友善。",
    suitable_for: "所有程度",
    fatigue_level: "低",
    skill_level: "低",
    ai_programming_note: "胸日收尾或新手主動作後的補強。",
    default_rep_range: [10, 15],
  },

  // ─── 徒手胸部 ────────────────────────────────────────
  {
    id: "push-up",
    name_zh: "伏地挺身",
    name_en: "Push-Up",
    category: "胸部",
    movement_pattern: "推",
    equipment: ["徒手"],
    primary_muscles: ["胸大肌"],
    secondary_muscles: ["三頭肌", "肩前束", "核心"],
    muscle_emphasis_note: "經典徒手推；可調腳手位置、握距改變刺激。",
    variations: [
      { id: "standard", name_zh: "標準伏地挺身" },
      { id: "incline", name_zh: "上斜伏地挺身", emphasis_change: "更易，新手起點" },
      { id: "decline", name_zh: "下斜伏地挺身", emphasis_change: "偏上胸" },
      { id: "narrow", name_zh: "窄距伏地挺身", emphasis_change: "偏三頭" },
      { id: "wide", name_zh: "寬距伏地挺身", emphasis_change: "偏外胸" },
      { id: "explosive", name_zh: "爆發伏地挺身", note: "進階動作" },
    ],
    suitable_for: "所有程度",
    fatigue_level: "中",
    skill_level: "低",
    ai_programming_note: "無器材時的胸部主動作；新手用上斜版本。",
    default_rep_range: [8, 20],
  },
  {
    id: "chest-dip",
    name_zh: "雙槓撐體（胸版）",
    name_en: "Chest Dip",
    category: "胸部",
    movement_pattern: "推",
    equipment: ["雙槓"],
    primary_muscles: ["下胸"],
    secondary_muscles: ["三頭肌", "肩前束"],
    muscle_emphasis_note: "前傾偏胸；負重後是強大下胸動作。",
    suitable_for: "中階",
    fatigue_level: "高",
    skill_level: "中",
    ai_programming_note: "胸日主或副動作；新手用輔助版本。",
    default_rep_range: [6, 12],
  },
];
