import type { Exercise } from "../types";

export const CORE: Exercise[] = [
  // ─── 腹直肌類 ────────────────────────────────────────
  {
    id: "crunch",
    name_zh: "捲腹",
    name_en: "Crunch",
    category: "腹部核心",
    movement_pattern: "核心屈曲",
    equipment: ["徒手", "瑜伽墊"],
    primary_muscles: ["腹直肌（上腹）"],
    secondary_muscles: [],
    muscle_emphasis_note: "脊椎屈曲為主刺激上腹；不需把整個背抬離地面。",
    suitable_for: "所有程度",
    fatigue_level: "低",
    skill_level: "低",
    ai_programming_note: "新手核心入門，2-3 組 15-20 下。",
    default_rep_range: [15, 25],
  },
  {
    id: "sit-up",
    name_zh: "仰臥起坐",
    name_en: "Sit-Up",
    category: "腹部核心",
    movement_pattern: "核心屈曲",
    equipment: ["徒手", "瑜伽墊"],
    primary_muscles: ["腹直肌"],
    secondary_muscles: ["髖屈肌"],
    muscle_emphasis_note: "傳統仰臥起坐；下背壓力較大，新手或下背不適者改用捲腹。",
    suitable_for: "所有程度",
    fatigue_level: "低",
    skill_level: "低",
    ai_programming_note: "若下背沒問題可作為核心主動作之一。",
    default_rep_range: [10, 20],
  },
  {
    id: "machine-crunch",
    name_zh: "機械捲腹",
    name_en: "Machine Crunch",
    category: "腹部核心",
    movement_pattern: "核心屈曲",
    equipment: ["機械"],
    primary_muscles: ["腹直肌"],
    secondary_muscles: [],
    muscle_emphasis_note: "可加重量做漸進超負荷；對訓練腹肌有實際肥大幫助。",
    suitable_for: "所有程度",
    fatigue_level: "中",
    skill_level: "低",
    ai_programming_note: "想真正練粗腹肌者必排；用 3 組 10-15 下。",
    default_rep_range: [10, 15],
  },
  {
    id: "cable-crunch",
    name_zh: "滑輪跪姿捲腹",
    name_en: "Cable Crunch",
    category: "腹部核心",
    movement_pattern: "核心屈曲",
    equipment: ["滑輪", "繩索"],
    primary_muscles: ["腹直肌"],
    secondary_muscles: [],
    muscle_emphasis_note: "可漸進加重的腹肌動作之一；跪姿、雙手抱繩、捲縮脊椎。",
    suitable_for: "所有程度",
    fatigue_level: "中",
    skill_level: "中",
    ai_programming_note: "腹肌肥大主要動作之一；建議 3 組 10-15 下。",
    default_rep_range: [10, 15],
  },
  {
    id: "hanging-leg-raise",
    name_zh: "懸垂舉腿",
    name_en: "Hanging Leg Raise",
    category: "腹部核心",
    movement_pattern: "核心屈曲",
    equipment: ["引體向上桿"],
    primary_muscles: ["腹直肌（下腹）", "髖屈肌"],
    secondary_muscles: ["前臂", "握力"],
    muscle_emphasis_note: "懸吊讓下腹刺激最強；屈膝版本適合新手，直腿版本進階。",
    variations: [
      { id: "knee", name_zh: "屈膝抬腿", note: "新手版本" },
      { id: "straight", name_zh: "直腿抬腿", note: "進階版本" },
    ],
    suitable_for: "中階",
    fatigue_level: "中",
    skill_level: "中",
    ai_programming_note: "下腹塑形首選；握力不足可先用羅馬椅版本。",
    default_rep_range: [8, 15],
  },
  {
    id: "captains-chair-leg-raise",
    name_zh: "羅馬椅抬腿",
    name_en: "Captain's Chair Leg Raise",
    category: "腹部核心",
    movement_pattern: "核心屈曲",
    equipment: ["羅馬椅"],
    primary_muscles: ["腹直肌（下腹）", "髖屈肌"],
    secondary_muscles: [],
    muscle_emphasis_note: "羅馬椅支撐去除握力限制；下腹刺激比懸垂略低。",
    suitable_for: "所有程度",
    fatigue_level: "中",
    skill_level: "低",
    ai_programming_note: "懸垂版本握力不足者用此替代。",
    default_rep_range: [10, 15],
  },

  // ─── 側核心 ──────────────────────────────────────────
  {
    id: "side-plank",
    name_zh: "側棒式",
    name_en: "Side Plank",
    category: "腹部核心",
    movement_pattern: "核心抗旋轉",
    equipment: ["徒手", "瑜伽墊"],
    primary_muscles: ["腹斜肌"],
    secondary_muscles: ["核心穩定肌群"],
    muscle_emphasis_note: "抗側向塌陷；新手從膝蓋撐地版本起步。",
    variations: [
      { id: "standard", name_zh: "標準側棒式" },
      { id: "leg", name_zh: "抬腿側棒式", note: "進階" },
      { id: "dynamic", name_zh: "動態側棒式", note: "腰部上下動作" },
    ],
    suitable_for: "所有程度",
    fatigue_level: "低",
    skill_level: "低",
    ai_programming_note: "核心收尾必排；計時 30-45 秒。",
    default_rep_range: [-1, -1],
  },

  // ─── 抗伸展核心 ──────────────────────────────────────
  {
    id: "plank",
    name_zh: "棒式",
    name_en: "Plank",
    category: "腹部核心",
    movement_pattern: "核心抗伸展",
    equipment: ["徒手", "瑜伽墊"],
    primary_muscles: ["腹橫肌", "腹直肌"],
    secondary_muscles: ["臀大肌", "肩部穩定肌群"],
    muscle_emphasis_note: "抗脊椎塌陷的核心動作；維持骨盆中立比時間長更重要。",
    suitable_for: "所有程度",
    fatigue_level: "低",
    skill_level: "低",
    ai_programming_note: "新手核心首選；任何課表都可放尾段。",
    default_rep_range: [-1, -1],
  },
];
