import type { Exercise } from "../types";

export const FULL_BODY: Exercise[] = [
  {
    id: "trap-bar-deadlift",
    name_zh: "六角槓硬舉",
    name_en: "Trap Bar Deadlift",
    category: "全身性",
    movement_pattern: "髖鉸鏈",
    equipment: ["六角槓"],
    primary_muscles: ["臀大肌", "腿後肌群", "股四頭肌"],
    secondary_muscles: ["背部", "核心", "握力"],
    muscle_emphasis_note: "下背壓力較傳統硬舉小、技術門檻低；對新手非常友善。",
    suitable_for: "所有程度",
    fatigue_level: "高",
    skill_level: "中",
    ai_programming_note: "新手 / 恢復期想練全身硬舉時首選。",
    default_rep_range: [5, 8],
    is_compound_main: true,
  },
  {
    id: "burpee",
    name_zh: "波比跳",
    name_en: "Burpee",
    category: "全身性",
    movement_pattern: "心肺體能",
    equipment: ["徒手"],
    primary_muscles: ["全身"],
    secondary_muscles: ["心肺"],
    muscle_emphasis_note: "心肺與全身爆發；動作品質比速度重要。",
    suitable_for: "所有程度",
    fatigue_level: "高",
    skill_level: "中",
    ai_programming_note: "心肺收尾或減脂日 HIIT。",
    default_rep_range: [10, 20],
  },
  {
    id: "treadmill-sprint",
    name_zh: "跑步機衝刺",
    name_en: "Treadmill Sprint",
    category: "全身性",
    movement_pattern: "心肺體能",
    equipment: ["跑步機"],
    primary_muscles: ["腿"],
    secondary_muscles: ["心肺"],
    muscle_emphasis_note: "依速度與斜坡可調強度；HIIT 或穩定有氧皆可。",
    variations: [
      { id: "flat", name_zh: "平地衝刺" },
      { id: "incline", name_zh: "斜坡快走", note: "減脂日推薦" },
      { id: "interval", name_zh: "間歇跑" },
    ],
    suitable_for: "所有程度",
    fatigue_level: "中",
    skill_level: "低",
    ai_programming_note: "減脂目標的心肺收尾首選；斜坡快走 15-20 分鐘最實用。",
    default_rep_range: [-1, -1],
  },
  {
    id: "stair-climber",
    name_zh: "登階機",
    name_en: "Stair Climber",
    category: "全身性",
    movement_pattern: "心肺體能",
    equipment: ["登階機"],
    primary_muscles: ["臀大肌", "腿"],
    secondary_muscles: ["心肺"],
    muscle_emphasis_note: "心肺加臀腿；對膝蓋友善。",
    suitable_for: "所有程度",
    fatigue_level: "中",
    skill_level: "低",
    ai_programming_note: "減脂者的長時心肺；15-25 分鐘為主。",
    default_rep_range: [-1, -1],
  },
];
