import type { Exercise } from "../types";

export const LEGS: Exercise[] = [
  // ─── 深蹲類 ──────────────────────────────────────────
  {
    id: "back-squat",
    name_zh: "槓鈴背蹲",
    name_en: "Back Squat",
    category: "大腿下肢",
    movement_pattern: "蹲",
    equipment: ["槓鈴"],
    primary_muscles: ["股四頭肌", "臀大肌"],
    secondary_muscles: ["腿後肌群", "核心", "豎脊肌"],
    muscle_emphasis_note: "全身性下肢主動作；技術門檻較高。",
    suitable_for: "中階",
    fatigue_level: "高",
    skill_level: "高",
    ai_programming_note: "腿日王牌動作；新手先從機械或啞鈴入門。",
    default_rep_range: [5, 8],
    is_compound_main: true,
  },
  {
    id: "front-squat",
    name_zh: "前蹲",
    name_en: "Front Squat",
    category: "大腿下肢",
    movement_pattern: "蹲",
    equipment: ["槓鈴"],
    primary_muscles: ["股四頭肌"],
    secondary_muscles: ["核心", "上背"],
    muscle_emphasis_note: "槓位於前方，股四頭刺激更直接；技術要求較高。",
    suitable_for: "進階",
    fatigue_level: "高",
    skill_level: "高",
    ai_programming_note: "進階股四頭主動作；活動度不足者勿勉強。",
    default_rep_range: [5, 8],
    is_compound_main: true,
  },
  {
    id: "smith-squat",
    name_zh: "史密斯深蹲",
    name_en: "Smith Machine Squat",
    category: "大腿下肢",
    movement_pattern: "蹲",
    equipment: ["史密斯機"],
    primary_muscles: ["股四頭肌", "臀大肌"],
    secondary_muscles: ["腿後肌群"],
    muscle_emphasis_note: "軌道固定的深蹲；可獨自安全推大重量。",
    suitable_for: "所有程度",
    fatigue_level: "高",
    skill_level: "中",
    ai_programming_note: "缺保護或新手練蹲的好替代。",
    default_rep_range: [6, 12],
  },
  {
    id: "hack-squat",
    name_zh: "哈克深蹲",
    name_en: "Hack Squat",
    category: "大腿下肢",
    movement_pattern: "蹲",
    equipment: ["機械"],
    primary_muscles: ["股四頭肌"],
    secondary_muscles: ["臀大肌"],
    muscle_emphasis_note: "機械深蹲；偏股四頭，下背壓力較小。",
    suitable_for: "所有程度",
    fatigue_level: "高",
    skill_level: "低",
    ai_programming_note: "腿日股四頭主動作；新手友善。",
    default_rep_range: [8, 12],
  },
  {
    id: "leg-press",
    name_zh: "腿推",
    name_en: "Leg Press",
    category: "大腿下肢",
    movement_pattern: "蹲",
    equipment: ["機械"],
    primary_muscles: ["股四頭肌", "臀大肌"],
    secondary_muscles: ["腿後肌群"],
    muscle_emphasis_note: "腳位可調，刺激比例不同：腳低偏股四頭、腳高偏臀腿後、腳寬偏內收與臀、腳窄偏股四頭外側。",
    variations: [
      { id: "low", name_zh: "腿推（腳放低）", emphasis_change: "偏股四頭" },
      { id: "high", name_zh: "腿推（腳放高）", emphasis_change: "偏臀與腿後" },
      { id: "wide", name_zh: "腿推（寬站距）", emphasis_change: "偏內收與臀" },
      { id: "narrow", name_zh: "腿推（窄站距）", emphasis_change: "偏股四頭外側" },
    ],
    suitable_for: "所有程度",
    fatigue_level: "高",
    skill_level: "低",
    ai_programming_note: "新手腿日主動作首選；可大重量、安全。",
    default_rep_range: [8, 12],
  },
  {
    id: "bulgarian-split-squat",
    name_zh: "保加利亞分腿蹲",
    name_en: "Bulgarian Split Squat",
    category: "大腿下肢",
    movement_pattern: "蹲",
    equipment: ["啞鈴", "板凳"],
    primary_muscles: ["股四頭肌", "臀大肌"],
    secondary_muscles: ["核心", "腿後肌群"],
    muscle_emphasis_note: "單腳訓練；對核心穩定與單側肌力很有效。",
    suitable_for: "中階",
    fatigue_level: "高",
    skill_level: "中",
    ai_programming_note: "腿日中段補強；單側 8-10 下。",
    default_rep_range: [8, 12],
  },
  {
    id: "leg-extension",
    name_zh: "腿伸展",
    name_en: "Leg Extension",
    category: "大腿下肢",
    movement_pattern: "孤立訓練",
    equipment: ["機械"],
    primary_muscles: ["股四頭肌"],
    secondary_muscles: [],
    muscle_emphasis_note: "股四頭孤立度最高的動作；膝關節有問題者慢做、控制範圍。",
    suitable_for: "所有程度",
    fatigue_level: "中",
    skill_level: "低",
    ai_programming_note: "腿日後段股四頭收尾；高次數 12-15 下。",
    default_rep_range: [10, 15],
  },

  // ─── 腿後肌群 ────────────────────────────────────────
  {
    id: "romanian-deadlift",
    name_zh: "羅馬尼亞硬舉",
    name_en: "Romanian Deadlift",
    category: "大腿下肢",
    movement_pattern: "髖鉸鏈",
    equipment: ["槓鈴", "啞鈴"],
    primary_muscles: ["腿後肌群", "臀大肌"],
    secondary_muscles: ["豎脊肌", "核心"],
    muscle_emphasis_note: "髖鉸鏈代表動作；強調腿後伸展。",
    suitable_for: "所有程度",
    fatigue_level: "高",
    skill_level: "中",
    ai_programming_note: "腿日 / 拉日的髖鉸鏈主動作；新手用啞鈴版本。",
    default_rep_range: [6, 10],
    is_compound_main: true,
  },
  {
    id: "deadlift",
    name_zh: "傳統硬舉",
    name_en: "Conventional Deadlift",
    category: "大腿下肢",
    movement_pattern: "髖鉸鏈",
    equipment: ["槓鈴"],
    primary_muscles: ["腿後肌群", "臀大肌", "豎脊肌"],
    secondary_muscles: ["背闊肌", "斜方肌", "握力"],
    muscle_emphasis_note: "全身性大重量動作；技術門檻最高。",
    suitable_for: "進階",
    fatigue_level: "高",
    skill_level: "高",
    ai_programming_note: "進階主動作；新手 1 年內優先用 RDL。",
    default_rep_range: [3, 6],
    is_compound_main: true,
  },
  {
    id: "hip-thrust",
    name_zh: "臀推",
    name_en: "Hip Thrust",
    category: "大腿下肢",
    movement_pattern: "髖鉸鏈",
    equipment: ["槓鈴", "板凳"],
    primary_muscles: ["臀大肌"],
    secondary_muscles: ["腿後肌群", "核心"],
    muscle_emphasis_note: "臀大肌孤立度最高的負重動作。",
    suitable_for: "所有程度",
    fatigue_level: "中",
    skill_level: "中",
    ai_programming_note: "想練臀者必排；女性訓練需求高時優先放在腿日前段。",
    default_rep_range: [8, 12],
    is_compound_main: true,
  },
  {
    id: "sumo-deadlift",
    name_zh: "相撲硬舉",
    name_en: "Sumo Deadlift",
    category: "大腿下肢",
    movement_pattern: "髖鉸鏈",
    equipment: ["槓鈴"],
    primary_muscles: ["臀大肌", "腿後肌群", "內收肌"],
    secondary_muscles: ["背部", "握力"],
    muscle_emphasis_note: "寬站距、軀幹較直；下背壓力較傳統硬舉小。",
    suitable_for: "中階",
    fatigue_level: "高",
    skill_level: "中",
    ai_programming_note: "傳統硬舉的替代選項；對髖關節活動度好的人友善。",
    default_rep_range: [3, 6],
    is_compound_main: true,
  },

  // ─── 內收 / 外展 ─────────────────────────────────────
  {
    id: "hip-adduction",
    name_zh: "大腿內收機",
    name_en: "Hip Adduction Machine",
    category: "大腿下肢",
    movement_pattern: "孤立訓練",
    equipment: ["機械"],
    primary_muscles: ["內收肌"],
    secondary_muscles: [],
    muscle_emphasis_note: "孤立大腿內側；改善內側鬆弛與力量平衡。",
    suitable_for: "所有程度",
    fatigue_level: "低",
    skill_level: "低",
    ai_programming_note: "腿日尾段補強；非必排。",
    default_rep_range: [12, 15],
  },
  {
    id: "hip-abduction",
    name_zh: "大腿外展機",
    name_en: "Hip Abduction Machine",
    category: "大腿下肢",
    movement_pattern: "孤立訓練",
    equipment: ["機械"],
    primary_muscles: ["臀中肌", "臀小肌"],
    secondary_muscles: [],
    muscle_emphasis_note: "塑造臀部側面寬度；改善髖部穩定。",
    suitable_for: "所有程度",
    fatigue_level: "低",
    skill_level: "低",
    ai_programming_note: "腿日尾段；可作為臀部塑形補強。",
    default_rep_range: [12, 15],
  },
];
