import type { Exercise } from "../types";

export const SHOULDERS: Exercise[] = [
  // ─── 肩推類 ──────────────────────────────────────────
  {
    id: "barbell-overhead-press",
    name_zh: "槓鈴肩推",
    name_en: "Barbell Overhead Press",
    category: "肩膀",
    movement_pattern: "推",
    equipment: ["槓鈴"],
    primary_muscles: ["肩前束", "肩中束"],
    secondary_muscles: ["三頭肌", "核心"],
    muscle_emphasis_note: "整體肩部最具負荷潛力的推舉動作；核心需主動穩定。",
    suitable_for: "中階",
    fatigue_level: "高",
    skill_level: "中",
    ai_programming_note: "肩日主動作。新手先用啞鈴或機械肩推。",
    default_rep_range: [5, 8],
    is_compound_main: true,
  },
  {
    id: "dumbbell-shoulder-press",
    name_zh: "啞鈴肩推",
    name_en: "Dumbbell Shoulder Press",
    category: "肩膀",
    movement_pattern: "推",
    equipment: ["啞鈴", "板凳"],
    primary_muscles: ["肩前束", "肩中束"],
    secondary_muscles: ["三頭肌"],
    muscle_emphasis_note: "雙手獨立、活動度更大；坐姿穩定、站姿挑戰核心。",
    variations: [
      { id: "seated", name_zh: "坐姿啞鈴肩推" },
      { id: "standing", name_zh: "站姿啞鈴肩推", note: "增加核心參與" },
    ],
    suitable_for: "所有程度",
    fatigue_level: "中",
    skill_level: "中",
    ai_programming_note: "新手友善的肩部主動作。",
    default_rep_range: [8, 12],
    is_compound_main: true,
  },
  {
    id: "machine-shoulder-press",
    name_zh: "機械肩推",
    name_en: "Machine Shoulder Press",
    category: "肩膀",
    movement_pattern: "推",
    equipment: ["機械"],
    primary_muscles: ["肩前束", "肩中束"],
    secondary_muscles: ["三頭肌"],
    muscle_emphasis_note: "軌道固定，最容易掌握、最安全的肩推方式。",
    suitable_for: "所有程度",
    fatigue_level: "中",
    skill_level: "低",
    ai_programming_note: "新手 / 恢復期首選肩部主動作。",
    default_rep_range: [8, 12],
  },
  {
    id: "arnold-press",
    name_zh: "阿諾肩推",
    name_en: "Arnold Press",
    category: "肩膀",
    movement_pattern: "推",
    equipment: ["啞鈴", "板凳"],
    primary_muscles: ["肩前束", "肩中束"],
    secondary_muscles: ["三頭肌"],
    muscle_emphasis_note: "底部反握、推上時旋轉；三角肌全束參與較多。",
    suitable_for: "中階",
    fatigue_level: "中",
    skill_level: "中",
    ai_programming_note: "肩日中段補充動作；對肩部活動度受限者要小心。",
    default_rep_range: [8, 12],
  },
  {
    id: "landmine-press",
    name_zh: "地雷管肩推",
    name_en: "Landmine Press",
    category: "肩膀",
    movement_pattern: "推",
    equipment: ["地雷管", "槓鈴"],
    primary_muscles: ["肩前束", "上胸"],
    secondary_muscles: ["核心", "三頭肌"],
    muscle_emphasis_note: "推的軌跡為斜上，介於肩推與上胸臥推之間，肩關節壓力較小。",
    suitable_for: "所有程度",
    fatigue_level: "中",
    skill_level: "低",
    ai_programming_note: "肩膀活動度不足者、想兼顧上胸者優先。",
    default_rep_range: [8, 12],
  },

  // ─── 側平舉類 ────────────────────────────────────────
  {
    id: "dumbbell-lateral-raise",
    name_zh: "啞鈴側平舉",
    name_en: "Dumbbell Lateral Raise",
    category: "肩膀",
    movement_pattern: "孤立訓練",
    equipment: ["啞鈴"],
    primary_muscles: ["肩中束"],
    secondary_muscles: ["斜方肌上束"],
    muscle_emphasis_note: "塑造肩寬最重要的動作；輕重量、控制節奏勝於重量。",
    suitable_for: "所有程度",
    fatigue_level: "低",
    skill_level: "低",
    ai_programming_note: "肩日必排，2-4 組高次數即可。",
    default_rep_range: [12, 20],
  },
  {
    id: "cable-lateral-raise",
    name_zh: "滑輪側平舉",
    name_en: "Cable Lateral Raise",
    category: "肩膀",
    movement_pattern: "孤立訓練",
    equipment: ["滑輪"],
    primary_muscles: ["肩中束"],
    secondary_muscles: [],
    muscle_emphasis_note: "持續張力、底部不會卸載，比啞鈴版本刺激更穩定。",
    variations: [
      { id: "single", name_zh: "單手滑輪側平舉" },
      { id: "behind", name_zh: "側身單手滑輪側平舉", note: "底部段拉伸更多" },
    ],
    suitable_for: "所有程度",
    fatigue_level: "低",
    skill_level: "低",
    ai_programming_note: "進階肩寬塑形；可作為肩日後段補強。",
    default_rep_range: [12, 20],
  },
  {
    id: "leaning-lateral-raise",
    name_zh: "傾斜側平舉",
    name_en: "Leaning Lateral Raise",
    category: "肩膀",
    movement_pattern: "孤立訓練",
    equipment: ["啞鈴"],
    primary_muscles: ["肩中束"],
    secondary_muscles: [],
    muscle_emphasis_note: "扶柱傾斜，加大底部拉伸範圍，刺激更深。",
    suitable_for: "中階",
    fatigue_level: "低",
    skill_level: "中",
    ai_programming_note: "肩中束想再進階的選項。",
    default_rep_range: [12, 15],
  },

  // ─── 前平舉類 ────────────────────────────────────────
  {
    id: "plate-front-raise",
    name_zh: "槓片前平舉",
    name_en: "Plate Front Raise",
    category: "肩膀",
    movement_pattern: "孤立訓練",
    equipment: ["槓鈴"],
    primary_muscles: ["肩前束"],
    secondary_muscles: ["上胸"],
    muscle_emphasis_note: "槓片版本握把舒適、肩前束孤立度高。",
    suitable_for: "所有程度",
    fatigue_level: "低",
    skill_level: "低",
    ai_programming_note: "若肩前束不需特別練（已有臥推）可省略。",
    default_rep_range: [12, 15],
  },
  {
    id: "cable-front-raise",
    name_zh: "滑輪前平舉",
    name_en: "Cable Front Raise",
    category: "肩膀",
    movement_pattern: "孤立訓練",
    equipment: ["滑輪"],
    primary_muscles: ["肩前束"],
    secondary_muscles: [],
    muscle_emphasis_note: "持續張力版本前平舉。",
    suitable_for: "所有程度",
    fatigue_level: "低",
    skill_level: "低",
    ai_programming_note: "肩前束已被臥推練到時，可改練後三角而非前束。",
    default_rep_range: [12, 15],
  },

  // ─── 後三角類 ────────────────────────────────────────
  {
    id: "reverse-pec-deck",
    name_zh: "反向飛鳥（蝴蝶機）",
    name_en: "Reverse Pec Deck",
    category: "肩膀",
    movement_pattern: "拉",
    equipment: ["機械"],
    primary_muscles: ["肩後束"],
    secondary_muscles: ["菱形肌", "斜方肌中束"],
    muscle_emphasis_note: "後三角孤立度最高的機械動作。",
    suitable_for: "所有程度",
    fatigue_level: "低",
    skill_level: "低",
    ai_programming_note: "肩日或拉日尾端必排，姿勢久坐者更該補。",
    default_rep_range: [12, 15],
  },
  {
    id: "face-pull",
    name_zh: "臉拉",
    name_en: "Face Pull",
    category: "肩膀",
    movement_pattern: "拉",
    equipment: ["滑輪", "繩索"],
    primary_muscles: ["肩後束", "斜方肌中下束"],
    secondary_muscles: ["旋轉肌群"],
    muscle_emphasis_note: "肩胛穩定、後三角、旋轉肌群一起練；滑手機族必排。",
    suitable_for: "所有程度",
    fatigue_level: "低",
    skill_level: "低",
    ai_programming_note: "拉日 / 肩日收尾首選；持續高次數 (15-20) 為主。",
    default_rep_range: [12, 20],
  },
];
